-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["truckContainer"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -38.5, -394.5  ,  -44, -391  ,  -41, -395  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   36, 359  ,  -10.5, 203.5  ,  27, 241  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   604, -77  ,  607, -58  ,  607, -11  ,  578.5, -97.5  ,  593.5, -93.5  ,  598.5, -89.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   607, -11  ,  566, -50  ,  515.5, -124.5  ,  578.5, -97.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -37.5, -394.5  ,  239.5, -256.5  ,  -62, -361  ,  -44, -391  ,  -38.5, -394.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   381.5, -187.5  ,  -62, -361  ,  239.5, -256.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -588.5, -4.5  ,  -10.5, 203.5  ,  -106.5, 203.5  ,  -607.5, 45.5  ,  -608, 43  ,  -592, 0  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   544, 394  ,  512.5, 352.5  ,  566, -50  ,  607, -11  ,  600, 67  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   515.5, -124.5  ,  566, -50  ,  -61.5, -358.5  ,  -62, -361  ,  381.5, -187.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -4, 285  ,  37, 370  ,  -7.5, 390.5  ,  -8, 367  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37, 370  ,  -4, 261  ,  -10.5, 203.5  ,  36, 359  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -10.5, 203.5  ,  -7.5, 258.5  ,  -106.5, 203.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -10.5, 203.5  ,  -4, 261  ,  -7.5, 258.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37, 370  ,  -4, 285  ,  -4, 261  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   38.5, 370.5  ,  -7.5, 390.5  ,  37, 370  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   38.5, 370.5  ,  512.5, 352.5  ,  544, 394  ,  -7.5, 390.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -38.5, -394.5  ,  -44, -391  ,  -40.5, -395.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37.5, 370.5  ,  -4, 261  ,  -12.5, 202.5  ,  27, 241  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   605, -73  ,  607, -57  ,  607, -11  ,  573.5, -99.5  ,  593.5, -93.5  ,  599, -89  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   607, -11  ,  565.5, -50.5  ,  524.5, -120.5  ,  573.5, -99.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -589.5, -4.5  ,  -12.5, 202.5  ,  -106.5, 203.5  ,  -608, 45  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -37.5, -394.5  ,  381.5, -187.5  ,  565.5, -50.5  ,  -62, -359  ,  -44, -391  ,  -38.5, -394.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   524.5, -120.5  ,  565.5, -50.5  ,  381.5, -187.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   599, 75  ,  574, 240  ,  544, 394  ,  513, 352  ,  565.5, -50.5  ,  607, -11  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   544, 394  ,  -7.5, 390.5  ,  37.5, 370.5  ,  513, 352  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -12.5, 202.5  ,  -7.5, 258.5  ,  -106.5, 203.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -12.5, 202.5  ,  -4, 261  ,  -7.5, 258.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37.5, 370.5  ,  -4, 285  ,  -4, 261  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37.5, 370.5  ,  -7.5, 390.5  ,  -4, 285  }
                    }
                    
                    
                    
		}
		
		, 
		["garbage1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0.1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28.5, -47  ,  -13.5, -51  ,  -12.5, -51  ,  -31, -35.5  ,  -33, -41.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0.1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   30, -33.5  ,  5.5, -51  ,  20.5, -48  ,  28.5, -44  ,  32, -39.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0.1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   31, 37.5  ,  -24.5, 50  ,  -33, 6.5  ,  -33, -29.5  ,  -31, -35.5  ,  -12.5, -51  ,  5.5, -51  ,  30, -33.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0.1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   25, 49.5  ,  -24.5, 50  ,  31, 37.5  ,  29, 45.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0.1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -33, 6.5  ,  -24.5, 50  ,  -31, 44.5  }
                    }
                    
                    
                    
		}
		
		, 
		["garbage2"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0.1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -25, -51.5  ,  -5, -56.5  ,  -31.5, -34  ,  -33.5, -44  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0.1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   31.5, -40  ,  -4, -56.5  ,  21, -55.5  ,  31, -51.5  ,  34.5, -47  ,  34.5, -43  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0.1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -5, -56.5  ,  -4, -56.5  ,  31.5, -40  ,  33.5, -36  ,  -29, 55.5  ,  -35.5, 48  ,  -31.5, -34  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0.1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   23, 55.5  ,  -29, 55.5  ,  33.5, -36  ,  33.5, -18  ,  30.5, 43  ,  29.5, 48  }
                    }
                    
                    
                    
		}
		
		, 
		["garbage3"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0.1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   12.5, -47  ,  -16.5, -53  ,  -13.5, -70  ,  -10, -75.5  ,  -9, -75.5  ,  6, -74.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0.1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   31.5, 68  ,  26, 74.5  ,  -33.5, -12  ,  -22.5, -35  ,  12.5, -47  ,  32.5, -13  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0.1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -32.5, 67  ,  -33.5, -12  ,  26, 74.5  ,  -26, 74.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0.1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   12.5, -47  ,  -22.5, -35  ,  -16.5, -53  }
                    }
                    
                    
                    
		}
		
		, 
		["liftArm"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 3.3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -153.5, 35  ,  -144.5, 32  ,  115.5, 30  ,  146.5, 42  ,  -143.5, 44  ,  -155, 39.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3.3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   146.5, 42  ,  117, 29.5  ,  117, 17.5  ,  123.5, -45  ,  124.5, -45  ,  149, -39.5  ,  154, 37.5  ,  152.5, 40  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3.3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   123.5, -45  ,  117, 17.5  ,  113, -40.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3.3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   149, -39.5  ,  124.5, -45  ,  143.5, -44  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3.3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   117, 29.5  ,  146.5, 42  ,  115.5, 30  }
                    }
                    
                    
                    
		}
		
		, 
		["trashCanContainer"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   193, -34.5  ,  189, 33.5  ,  163, 161.5  ,  156, -150.5  ,  158.5, -163  ,  159.5, -163  ,  190.5, -158  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -168, 108.5  ,  -170, 138.5  ,  -184.5, 160  ,  -193.5, -152  ,  -165, -152.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -168, 144.5  ,  -184.5, 160  ,  -170, 138.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -129.5, 150  ,  -184.5, 160  ,  -168, 144.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   33.5, 158  ,  -184.5, 160  ,  -129.5, 150  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   132.5, 150  ,  163, 161.5  ,  -63.5, 152  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   137, 148.5  ,  163, 161.5  ,  132.5, 150  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   156, -150.5  ,  163, 161.5  ,  137, 148.5  }
                    }
                    
                    
                    
		}
		
		, 
		["trashCan"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   178.5, -317  ,  186.5, -289  ,  170, -315  ,  169, -326.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   163.5, 72  ,  159.5, 38  ,  170, -315  ,  186.5, -289  ,  191.5, 65  ,  187.5, 84  ,  176, 90.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   138, 325.5  ,  107, 315.5  ,  79, 292.5  ,  197, 186.5  ,  219.5, 225  ,  215.5, 278  ,  184, 314.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -222.5, 259  ,  -195.5, 124  ,  -177, 119  ,  146, 164.5  ,  197, 186.5  ,  79, 292.5  ,  -196, 292.5  ,  -218.5, 277  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   197, 186.5  ,  146, 164.5  ,  174.5, 172  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -218.5, -118  ,  -202, -262  ,  -177, 119  ,  -195.5, 124  ,  -222.5, -15  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -202, -262  ,  -218.5, -118  ,  -209.5, -297  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   159.5, 38  ,  135.5, 127  ,  129, 117  ,  170, -315  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   146, 164.5  ,  -177, 119  ,  129, 117  ,  135.5, 127  }
                    }
                    
                    
                    
		}
		
		, 
		["wheel1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2.3, friction = 0.1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   89.5, 165.5  ,  11.5, 186.5  ,  -169.5, 89.5  ,  -187, 47  ,  -14.5, -187.5  ,  192, -13  ,  185, 51  ,  149, 118  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2.3, friction = 0.1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -90.5, -166.5  ,  -14.5, -187.5  ,  -187, 47  ,  -193, 12  ,  -186, -52  ,  -150, -119  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2.3, friction = 0.1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -169.5, 89.5  ,  11.5, 186.5  ,  -57.5, 178.5  ,  -121.5, 145.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2.3, friction = 0.1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   168.5, -90.5  ,  186, -48  ,  192, -13  ,  -14.5, -187.5  ,  -13.5, -187.5  ,  59.5, -178.5  ,  122, -145  }
                    }
                    
                    
                    
		}
		
		, 
		["wheel2"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2.3, friction = 0.1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    radius = 187.024
                    }
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   89.5, 165.5  ,  11.5, 186.5  ,  -169.5, 89.5  ,  -187, 47  ,  -14.5, -187.5  ,  192, -13  ,  185, 51  ,  149, 118  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -90.5, -166.5  ,  -14.5, -187.5  ,  -187, 47  ,  -193, 12  ,  -186, -52  ,  -150, -119  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -169.5, 89.5  ,  11.5, 186.5  ,  -57.5, 178.5  ,  -121.5, 145.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   168.5, -90.5  ,  186, -48  ,  192, -13  ,  -14.5, -187.5  ,  -13.5, -187.5  ,  59.5, -178.5  ,  122, -145  }
                    }
                    
                    
                    
		}
		
		, 
		["trashTruck"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   716.5, -241  ,  754.5, -104  ,  393, -348.5  ,  674.5, -348  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   866.5, -55  ,  864.5, 250  ,  754.5, -104  ,  834, -93.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   864.5, 250  ,  843.5, 277  ,  807, 289.5  ,  393, 289.5  ,  342, 257.5  ,  338.5, -68  ,  393, -348.5  ,  754.5, -104  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -864.5, 302  ,  -835, 312  ,  -726, 362  ,  -646, 409.5  ,  -753, 398.5  ,  -811, 379.5  ,  -846, 350.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   342, 257.5  ,  393, 289.5  ,  361, 278.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   393, -348.5  ,  338.5, -68  ,  333.5, -283  ,  339, -310.5  ,  356, -333.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   292, 357.5  ,  319.5, 256  ,  320.5, 303  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   198, 405.5  ,  253, 372  ,  292, 357.5  ,  253, 390.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   319.5, 256  ,  318, -62.5  ,  338.5, -68  ,  342, 257.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   292, 357.5  ,  253, 372  ,  276, -389  ,  309.5, -390  ,  319.5, 256  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   309.5, -390  ,  276, -389  ,  -423, -410.5  ,  297.5, -409  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -835, 312  ,  -864.5, 302  ,  -869.5, -19  ,  -862.5, -40  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   253, 372  ,  198, 405.5  ,  -646, 409.5  ,  -726, 362  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

